// Curated "phrase bank" for the Suggestions tab — Tony browses and picks individual phrases to
// add to his own deck at his own pace, rather than being handed a starter deck all at once.
// Categories are deliberately ordered (SUGGESTION_CATEGORY_ORDER below) so Romantic and Funny &
// Playful surface first, since that's what Tony wants to lean into early on.

const SUGGESTED_PHRASES = [
  // ---- Romantic ----
  { id: "s301", cat: "Romantic", id_text: "Aku sayang kamu", en: "I care about you / I love you", note: "\"Sayang\" is the everyday, warm word for love — used constantly between couples." },
  { id: "s302", cat: "Romantic", id_text: "Aku cinta kamu", en: "I love you", note: "\"Cinta\" is a deeper, more deliberate word for love than \"sayang\"." },
  { id: "s303", cat: "Romantic", id_text: "Kamu cantik banget", en: "You're so beautiful", note: "" },
  { id: "s304", cat: "Romantic", id_text: "Kamu cantik hari ini", en: "You look beautiful today", note: "" },
  { id: "s305", cat: "Romantic", id_text: "Kamu bikin aku senyum terus", en: "You make me smile all the time", note: "" },
  { id: "s306", cat: "Romantic", id_text: "Aku kangen kamu", en: "I miss you", note: "\"Kangen\" is the natural everyday word for missing someone." },
  { id: "s307", cat: "Romantic", id_text: "Aku kangen banget sama kamu", en: "I miss you so much", note: "" },
  { id: "s308", cat: "Romantic", id_text: "Kamu itu segalanya buat aku", en: "You mean everything to me", note: "" },
  { id: "s309", cat: "Romantic", id_text: "Aku beruntung punya kamu", en: "I'm lucky to have you", note: "" },
  { id: "s310", cat: "Romantic", id_text: "Kamu spesial banget", en: "You're really special", note: "" },
  { id: "s311", cat: "Romantic", id_text: "Aku nggak bisa berhenti mikirin kamu", en: "I can't stop thinking about you", note: "" },
  { id: "s312", cat: "Romantic", id_text: "Peluk aku", en: "Hug me", note: "" },
  { id: "s313", cat: "Romantic", id_text: "Aku mau peluk kamu terus", en: "I want to hug you forever", note: "" },
  { id: "s314", cat: "Romantic", id_text: "Senyum kamu bikin hari aku indah", en: "Your smile makes my day", note: "" },
  { id: "s315", cat: "Romantic", id_text: "Aku jatuh cinta sama kamu", en: "I've fallen in love with you", note: "" },
  { id: "s316", cat: "Romantic", id_text: "Kamu bikin hatiku berdebar", en: "You make my heart race", note: "" },
  { id: "s317", cat: "Romantic", id_text: "Aku mau selalu di samping kamu", en: "I want to always be by your side", note: "" },
  { id: "s318", cat: "Romantic", id_text: "Sayang, aku di sini", en: "Babe, I'm here", note: "" },
  { id: "s319", cat: "Romantic", id_text: "Sayangku", en: "My love / my darling", note: "Pet name — \"sayang\" plus \"-ku\" (my)." },
  { id: "s320", cat: "Romantic", id_text: "Cintaku", en: "My love", note: "Pet name — \"cinta\" plus \"-ku\" (my)." },
  { id: "s321", cat: "Romantic", id_text: "Kamu pasangan terbaik", en: "You're the best partner", note: "" },
  { id: "s322", cat: "Romantic", id_text: "Terima kasih sudah jadi kekasihku", en: "Thank you for being my girlfriend", note: "" },
  { id: "s323", cat: "Romantic", id_text: "Aku bahagia banget sama kamu", en: "I'm so happy with you", note: "" },
  { id: "s324", cat: "Romantic", id_text: "Kamu buat hidupku lebih berwarna", en: "You make my life more colorful", note: "" },
  { id: "s325", cat: "Romantic", id_text: "Aku ingin selalu bersama kamu", en: "I want to always be with you", note: "" },
  { id: "s326", cat: "Romantic", id_text: "Kamu adalah alasan aku tersenyum", en: "You're the reason I smile", note: "" },
  { id: "s327", cat: "Romantic", id_text: "Aku sayang kamu apa adanya", en: "I love you just as you are", note: "" },
  { id: "s328", cat: "Romantic", id_text: "Kamu bikin aku jadi lebih baik", en: "You make me a better person", note: "" },
  { id: "s329", cat: "Romantic", id_text: "Cium aku", en: "Kiss me", note: "" },
  { id: "s330", cat: "Romantic", id_text: "Aku kangen ciuman kamu", en: "I miss your kiss", note: "" },
  { id: "s331", cat: "Romantic", id_text: "Tidur nyenyak, sayang", en: "Sleep well, my love", note: "" },
  { id: "s332", cat: "Romantic", id_text: "Selamat pagi, sayang", en: "Good morning, love", note: "" },
  { id: "s333", cat: "Romantic", id_text: "Selamat malam, cintaku", en: "Good night, my love", note: "" },
  { id: "s334", cat: "Romantic", id_text: "Aku selalu mikirin kamu", en: "I'm always thinking of you", note: "" },
  { id: "s335", cat: "Romantic", id_text: "Kamu itu impian aku", en: "You're my dream come true", note: "" },
  { id: "s336", cat: "Romantic", id_text: "Aku nggak sabar ketemu kamu", en: "I can't wait to see you", note: "" },
  { id: "s337", cat: "Romantic", id_text: "Aku sayang senyum kamu", en: "I love your smile", note: "" },
  { id: "s338", cat: "Romantic", id_text: "Selamanya sama kamu", en: "Forever with you", note: "" },
  { id: "s339", cat: "Romantic", id_text: "Kamu ganteng", en: "You're handsome", note: "Useful to know even if it's usually said to you, not by you." },
  { id: "s340", cat: "Romantic", id_text: "Kamu itu cinta pertama aku di Indonesia", en: "You're my first love in Indonesia", note: "A cute, light-hearted line." },

  // ---- Funny & Playful ----
  { id: "s261", cat: "Funny & Playful", id_text: "Kamu lucu banget!", en: "You're so funny!", note: "" },
  { id: "s262", cat: "Funny & Playful", id_text: "Gombal banget!", en: "So cheesy!", note: "\"Gombal\" is the specific Indonesian word for a cheesy pickup line or flattery." },
  { id: "s263", cat: "Funny & Playful", id_text: "Apaan sih!", en: "What?!", note: "Playful exasperation." },
  { id: "s264", cat: "Funny & Playful", id_text: "Duh, apaan sih?!", en: "Ugh, what now?!", note: "" },
  { id: "s265", cat: "Funny & Playful", id_text: "Serius amat sih!", en: "You're being way too serious!", note: "Teasing." },
  { id: "s266", cat: "Funny & Playful", id_text: "Aku cuma bercanda", en: "I'm just kidding", note: "" },
  { id: "s267", cat: "Funny & Playful", id_text: "Jangan baper", en: "Don't take it too personally", note: "\"Baper\" (from \"bawa perasaan\") is extremely common slang for getting emotionally invested." },
  { id: "s268", cat: "Funny & Playful", id_text: "Kamu berlebihan deh", en: "You're being dramatic", note: "" },
  { id: "s269", cat: "Funny & Playful", id_text: "Aduh, malu-maluin!", en: "Ugh, so embarrassing!", note: "Playful, not serious." },
  { id: "s270", cat: "Funny & Playful", id_text: "Kamu aneh, tapi lucu", en: "You're weird, but funny", note: "" },
  { id: "s271", cat: "Funny & Playful", id_text: "Dasar kamu!", en: "Oh you!", note: "Playful mock-scolding." },
  { id: "s272", cat: "Funny & Playful", id_text: "Awas ya!", en: "Watch out!", note: "Playfully threatening." },
  { id: "s273", cat: "Funny & Playful", id_text: "Ih, nakal!", en: "Ooh, naughty!", note: "Playful." },
  { id: "s274", cat: "Funny & Playful", id_text: "Kamu ini bikin gemas!", en: "You're so cute it's exasperating!", note: "\"Gemas\" is that specific feeling of adorable frustration — very Indonesian, no direct English word." },
  { id: "s275", cat: "Funny & Playful", id_text: "Kamu jail deh", en: "You're mischievous", note: "" },
  { id: "s276", cat: "Funny & Playful", id_text: "Iseng aja", en: "Just messing around", note: "" },
  { id: "s277", cat: "Funny & Playful", id_text: "Jangan ngambek dong", en: "Don't sulk", note: "" },
  { id: "s278", cat: "Funny & Playful", id_text: "Kok gitu sih?", en: "Why like that though?", note: "Teasing." },
  { id: "s279", cat: "Funny & Playful", id_text: "Kamu lebay", en: "You're being over the top", note: "\"Lebay\" is slang for exaggerated/dramatic behavior." },
  { id: "s280", cat: "Funny & Playful", id_text: "Aku becanda kok", en: "I'm just joking", note: "" },
  { id: "s281", cat: "Funny & Playful", id_text: "Kamu bikin aku ketawa terus", en: "You keep making me laugh", note: "" },
  { id: "s282", cat: "Funny & Playful", id_text: "Receh banget humor kamu", en: "Your jokes are so silly", note: "\"Receh\" literally means \"small change/coins\" — slang for corny, low-effort humor." },
  { id: "s283", cat: "Funny & Playful", id_text: "Kocak deh kamu", en: "You're hilarious", note: "" },
  { id: "s284", cat: "Funny & Playful", id_text: "Aduh, kamu ada-ada aja", en: "Oh, you and your antics", note: "" },
  { id: "s285", cat: "Funny & Playful", id_text: "Sok tau deh", en: "You're such a know-it-all", note: "Playful teasing." },
  { id: "s286", cat: "Funny & Playful", id_text: "Nggak nyangka kamu selucu ini", en: "I didn't expect you to be this funny", note: "" },
  { id: "s287", cat: "Funny & Playful", id_text: "Muka kamu lucu kalau lagi bingung", en: "Your face is funny when you're confused", note: "" },
  { id: "s288", cat: "Funny & Playful", id_text: "Kamu penggoda ya", en: "You're such a tease", note: "" },
  { id: "s289", cat: "Funny & Playful", id_text: "Awas, aku gelitikin!", en: "Watch out, I'll tickle you!", note: "" },
  { id: "s290", cat: "Funny & Playful", id_text: "Jangan gitu, aku ketawa mulu jadinya", en: "Stop it, you're making me laugh nonstop", note: "" },
  { id: "s291", cat: "Funny & Playful", id_text: "Kamu emang paling bisa", en: "You're really something", note: "Playful admiration." },
  { id: "s292", cat: "Funny & Playful", id_text: "Sotoy amat", en: "Such a know-it-all", note: "Casual synonym for \"sok tau\"." },
  { id: "s293", cat: "Funny & Playful", id_text: "Kamu ini ada-ada saja", en: "You're always up to something", note: "" },
  { id: "s294", cat: "Funny & Playful", id_text: "Aduh, kamu bikin baper!", en: "Ugh, you're making me all emotional!", note: "About a sweet gesture, not a fight." },
  { id: "s295", cat: "Funny & Playful", id_text: "Jangan ngeledek dong", en: "Don't tease me", note: "" },
  { id: "s296", cat: "Funny & Playful", id_text: "Aku bercanda doang", en: "I'm only joking", note: "" },
  { id: "s297", cat: "Funny & Playful", id_text: "Kalem dulu", en: "Chill out / relax", note: "" },
  { id: "s298", cat: "Funny & Playful", id_text: "Kamu suka banget godain aku ya", en: "You really like teasing me, huh", note: "" },
  { id: "s299", cat: "Funny & Playful", id_text: "Ish, kamu deh!", en: "Ugh, you!", note: "Playful exasperated affection." },
  { id: "s300", cat: "Funny & Playful", id_text: "Gila!", en: "Wow! / Crazy!", note: "Very common exclamation of surprise — not literally about anger or insanity." },

  // ---- Meeting Her Family ----
  { id: "s201", cat: "Meeting Her Family", id_text: "Selamat siang, Pak", en: "Good afternoon, sir", note: "Respectful, to an older man." },
  { id: "s202", cat: "Meeting Her Family", id_text: "Selamat siang, Bu", en: "Good afternoon, ma'am", note: "Respectful, to an older woman." },
  { id: "s203", cat: "Meeting Her Family", id_text: "Bapak", en: "Father / respectful term for an older man", note: "" },
  { id: "s204", cat: "Meeting Her Family", id_text: "Ibu", en: "Mother / respectful term for an older woman", note: "" },
  { id: "s205", cat: "Meeting Her Family", id_text: "Om", en: "Uncle", note: "Also used respectfully for older men close to the family, not just literal uncles." },
  { id: "s206", cat: "Meeting Her Family", id_text: "Tante", en: "Aunt", note: "Also used respectfully for older women close to the family." },
  { id: "s207", cat: "Meeting Her Family", id_text: "Kakak", en: "Older sibling", note: "Also used respectfully for someone a bit older than you." },
  { id: "s208", cat: "Meeting Her Family", id_text: "Adik", en: "Younger sibling", note: "" },
  { id: "s209", cat: "Meeting Her Family", id_text: "Senang sekali bisa bertemu Bapak dan Ibu", en: "I'm very happy to meet you both", note: "To her parents." },
  { id: "s210", cat: "Meeting Her Family", id_text: "Terima kasih sudah menerima saya di rumah ini", en: "Thank you for welcoming me into your home", note: "" },
  { id: "s211", cat: "Meeting Her Family", id_text: "Rumahnya bagus sekali", en: "Your home is lovely", note: "" },
  { id: "s212", cat: "Meeting Her Family", id_text: "Terima kasih atas jamuannya", en: "Thank you for your hospitality", note: "" },
  { id: "s213", cat: "Meeting Her Family", id_text: "Masakannya enak sekali, Bu", en: "Your cooking is delicious, ma'am", note: "" },
  { id: "s214", cat: "Meeting Her Family", id_text: "Mohon maaf kalau bahasa Indonesia saya belum lancar", en: "I apologize if my Indonesian isn't fluent yet", note: "" },
  { id: "s215", cat: "Meeting Her Family", id_text: "Saya sedang belajar bahasa Indonesia untuk keluarga ini", en: "I'm learning Indonesian for this family", note: "" },
  { id: "s216", cat: "Meeting Her Family", id_text: "Apa kabar, Pak?", en: "How are you, sir?", note: "" },
  { id: "s217", cat: "Meeting Her Family", id_text: "Apa kabar, Bu?", en: "How are you, ma'am?", note: "" },
  { id: "s218", cat: "Meeting Her Family", id_text: "Sudah lama tinggal di sini?", en: "Have you lived here long?", note: "" },
  { id: "s219", cat: "Meeting Her Family", id_text: "Berapa bersaudara?", en: "How many siblings do you have?", note: "" },
  { id: "s220", cat: "Meeting Her Family", id_text: "Saya senang berada di sini", en: "I'm happy to be here", note: "" },
  { id: "s221", cat: "Meeting Her Family", id_text: "Terima kasih sudah mengundang saya", en: "Thank you for inviting me", note: "" },
  { id: "s222", cat: "Meeting Her Family", id_text: "Ini untuk Bapak dan Ibu", en: "This is for you both", note: "Giving a gift." },
  { id: "s223", cat: "Meeting Her Family", id_text: "Semoga berkenan", en: "I hope you like it", note: "Offering a gift, humbly." },
  { id: "s224", cat: "Meeting Her Family", id_text: "Saya akan selalu menjaganya dengan baik", en: "I will always take good care of her", note: "" },
  { id: "s225", cat: "Meeting Her Family", id_text: "Keluarga ini sangat ramah", en: "This family is very welcoming", note: "" },
  { id: "s226", cat: "Meeting Her Family", id_text: "Saya hormat kepada Bapak dan Ibu", en: "I have great respect for you both", note: "" },
  { id: "s227", cat: "Meeting Her Family", id_text: "Boleh saya bantu di dapur?", en: "May I help in the kitchen?", note: "" },
  { id: "s228", cat: "Meeting Her Family", id_text: "Biar saya yang bawa", en: "Let me carry that", note: "" },
  { id: "s229", cat: "Meeting Her Family", id_text: "Silakan duduk", en: "Please, have a seat", note: "" },
  { id: "s230", cat: "Meeting Her Family", id_text: "Mari makan bersama", en: "Let's eat together", note: "" },
  { id: "s231", cat: "Meeting Her Family", id_text: "Selamat makan, semuanya", en: "Enjoy the meal, everyone", note: "" },
  { id: "s232", cat: "Meeting Her Family", id_text: "Terima kasih banyak, Pak", en: "Thank you very much, sir", note: "" },
  { id: "s233", cat: "Meeting Her Family", id_text: "Terima kasih banyak, Bu", en: "Thank you very much, ma'am", note: "" },
  { id: "s234", cat: "Meeting Her Family", id_text: "Semoga sehat selalu", en: "Wishing you continued good health", note: "" },
  { id: "s235", cat: "Meeting Her Family", id_text: "Maaf kalau saya merepotkan", en: "Sorry if I'm causing any trouble", note: "" },
  { id: "s236", cat: "Meeting Her Family", id_text: "Tidak usah repot-repot", en: "Please don't go to any trouble", note: "" },
  { id: "s237", cat: "Meeting Her Family", id_text: "Saya akan sering ke sini", en: "I'll come here often", note: "" },
  { id: "s238", cat: "Meeting Her Family", id_text: "Terima kasih sudah menyambut saya dengan hangat", en: "Thank you for welcoming me so warmly", note: "" },
  { id: "s239", cat: "Meeting Her Family", id_text: "Bagaimana kabar keluarga?", en: "How is the family?", note: "" },
  { id: "s240", cat: "Meeting Her Family", id_text: "Salam untuk keluarga", en: "My regards to the family", note: "" },
  { id: "s241", cat: "Meeting Her Family", id_text: "Saya suka sekali dengan budaya Indonesia", en: "I really like Indonesian culture", note: "" },
  { id: "s242", cat: "Meeting Her Family", id_text: "Ini pertama kali saya ke Indonesia", en: "This is my first time in Indonesia", note: "" },
  { id: "s243", cat: "Meeting Her Family", id_text: "Terima kasih sudah mengajari saya", en: "Thank you for teaching me", note: "" },
  { id: "s244", cat: "Meeting Her Family", id_text: "Saya akan belajar lebih banyak", en: "I'll learn more", note: "" },
  { id: "s245", cat: "Meeting Her Family", id_text: "Semoga kita sering bertemu lagi", en: "I hope we meet again often", note: "" },
  { id: "s246", cat: "Meeting Her Family", id_text: "Saya sangat menghargai ini", en: "I really appreciate this", note: "" },
  { id: "s247", cat: "Meeting Her Family", id_text: "Sampai jumpa lagi, Pak", en: "See you again, sir", note: "" },
  { id: "s248", cat: "Meeting Her Family", id_text: "Sampai jumpa lagi, Bu", en: "See you again, ma'am", note: "" },
  { id: "s249", cat: "Meeting Her Family", id_text: "Terima kasih sudah menerima saya sebagai bagian dari keluarga", en: "Thank you for accepting me as part of the family", note: "" },
  { id: "s250", cat: "Meeting Her Family", id_text: "Semoga Bapak dan Ibu selalu bahagia", en: "I wish you both continued happiness", note: "" },
  { id: "s251", cat: "Meeting Her Family", id_text: "Boleh saya foto bersama?", en: "May I take a photo together?", note: "" },
  { id: "s252", cat: "Meeting Her Family", id_text: "Ini kenang-kenangan dari Australia", en: "This is a small gift from Australia", note: "\"Kenang-kenangan\" = a keepsake/souvenir." },
  { id: "s253", cat: "Meeting Her Family", id_text: "Saya harap bisa datang lagi", en: "I hope I can come again", note: "" },
  { id: "s254", cat: "Meeting Her Family", id_text: "Terima kasih untuk semuanya", en: "Thank you for everything", note: "" },
  { id: "s255", cat: "Meeting Her Family", id_text: "Semoga panjang umur, Pak", en: "Wishing you a long life, sir", note: "" },
  { id: "s256", cat: "Meeting Her Family", id_text: "Ini sangat berarti buat saya", en: "This means a lot to me", note: "" },
  { id: "s257", cat: "Meeting Her Family", id_text: "Boleh saya panggil Om?", en: "May I call you Om?", note: "Asking permission to use the familiar/respectful term for an older man close to the family." },
  { id: "s258", cat: "Meeting Her Family", id_text: "Boleh saya panggil Tante?", en: "May I call you Tante?", note: "The female equivalent of Om." },
  { id: "s259", cat: "Meeting Her Family", id_text: "Saya senang jadi bagian dari acara ini", en: "I'm happy to be part of this occasion", note: "" },
  { id: "s260", cat: "Meeting Her Family", id_text: "Restu Bapak dan Ibu sangat berarti", en: "Your blessing means a great deal", note: "A meaningful, respectful line in Indonesian family culture." },

  // ---- Everyday Chat with Friends ----
  { id: "s241b", cat: "Everyday Chat with Friends", id_text: "Gue", en: "I / me", note: "Casual Jakarta register, used with friends rather than \"saya\"." },
  { id: "s242b", cat: "Everyday Chat with Friends", id_text: "Lo", en: "You", note: "Casual Jakarta register, used with friends rather than \"kamu\"." },
  { id: "s243b", cat: "Everyday Chat with Friends", id_text: "Apa kabar, bro?", en: "How's it going, bro?", note: "" },
  { id: "s244b", cat: "Everyday Chat with Friends", id_text: "Lagi ngapain?", en: "What are you up to?", note: "" },
  { id: "s245b", cat: "Everyday Chat with Friends", id_text: "Santai aja", en: "Just relax / take it easy", note: "" },
  { id: "s246b", cat: "Everyday Chat with Friends", id_text: "Serius?", en: "Really? / Seriously?", note: "" },
  { id: "s247b", cat: "Everyday Chat with Friends", id_text: "Yang benar?", en: "Really?", note: "Checking something surprising." },
  { id: "s248b", cat: "Everyday Chat with Friends", id_text: "Keren banget!", en: "So cool!", note: "" },
  { id: "s249b", cat: "Everyday Chat with Friends", id_text: "Mantap!", en: "Awesome! / Nice!", note: "" },
  { id: "s250b", cat: "Everyday Chat with Friends", id_text: "Asik!", en: "Fun! / Nice!", note: "" },
  { id: "s251b", cat: "Everyday Chat with Friends", id_text: "Boleh juga", en: "Not bad / sounds good", note: "" },
  { id: "s252b", cat: "Everyday Chat with Friends", id_text: "Gue setuju", en: "I agree", note: "" },
  { id: "s253b", cat: "Everyday Chat with Friends", id_text: "Gue nggak setuju", en: "I disagree", note: "" },
  { id: "s254b", cat: "Everyday Chat with Friends", id_text: "Kayaknya sih gitu", en: "I think so", note: "" },
  { id: "s255b", cat: "Everyday Chat with Friends", id_text: "Nggak tau deh", en: "I have no idea", note: "" },
  { id: "s256b", cat: "Everyday Chat with Friends", id_text: "Emang sih", en: "Yeah, true", note: "Conceding a point." },
  { id: "s257b", cat: "Everyday Chat with Friends", id_text: "Ya udah", en: "Alright then / never mind", note: "" },
  { id: "s258b", cat: "Everyday Chat with Friends", id_text: "Gimana?", en: "How is it? / What do you think?", note: "" },
  { id: "s259b", cat: "Everyday Chat with Friends", id_text: "Gimana caranya?", en: "How do you do it?", note: "" },
  { id: "s260b", cat: "Everyday Chat with Friends", id_text: "Kenapa sih?", en: "Why though?", note: "" },
  { id: "s261b", cat: "Everyday Chat with Friends", id_text: "Ntar deh", en: "Later", note: "Casual for \"nanti\"." },
  { id: "s262b", cat: "Everyday Chat with Friends", id_text: "Bentar", en: "Just a sec", note: "" },
  { id: "s263b", cat: "Everyday Chat with Friends", id_text: "Tunggu bentar", en: "Wait a sec", note: "" },
  { id: "s264b", cat: "Everyday Chat with Friends", id_text: "Udah, ah", en: "Enough already", note: "" },
  { id: "s265b", cat: "Everyday Chat with Friends", id_text: "Capek deh", en: "So tired", note: "" },
  { id: "s266b", cat: "Everyday Chat with Friends", id_text: "Laper nih", en: "I'm hungry", note: "Casual, using the particle \"nih\"." },
  { id: "s267b", cat: "Everyday Chat with Friends", id_text: "Yuk, jalan-jalan", en: "Let's go hang out", note: "" },
  { id: "s268b", cat: "Everyday Chat with Friends", id_text: "Ikut dong", en: "I want to come too", note: "" },
  { id: "s269b", cat: "Everyday Chat with Friends", id_text: "Boleh ikut nggak?", en: "Can I come along?", note: "" },
  { id: "s270b", cat: "Everyday Chat with Friends", id_text: "Nanti gue kabarin", en: "I'll let you know later", note: "" },
  { id: "s271b", cat: "Everyday Chat with Friends", id_text: "Oke deh", en: "Okay, sure", note: "" },
  { id: "s272b", cat: "Everyday Chat with Friends", id_text: "Sip", en: "Cool / got it", note: "" },
  { id: "s273b", cat: "Everyday Chat with Friends", id_text: "Beneran?", en: "For real?", note: "" },
  { id: "s274b", cat: "Everyday Chat with Friends", id_text: "Ih, jangan gitu dong", en: "Come on, don't be like that", note: "" },
  { id: "s275b", cat: "Everyday Chat with Friends", id_text: "Jangan lupa ya", en: "Don't forget, okay", note: "" },
  { id: "s276b", cat: "Everyday Chat with Friends", id_text: "Nanti telepon gue ya", en: "Call me later, okay", note: "" },
  { id: "s277b", cat: "Everyday Chat with Friends", id_text: "Gue kangen kalian", en: "I miss you guys", note: "" },
  { id: "s278b", cat: "Everyday Chat with Friends", id_text: "Kapan ketemuan lagi?", en: "When are we meeting up again?", note: "" },
  { id: "s279b", cat: "Everyday Chat with Friends", id_text: "Gue lagi sibuk", en: "I'm busy right now", note: "" },
  { id: "s280b", cat: "Everyday Chat with Friends", id_text: "Ada waktu nggak?", en: "Do you have time?", note: "" },
  { id: "s281b", cat: "Everyday Chat with Friends", id_text: "Gimana kabarnya?", en: "How have you been?", note: "" },
  { id: "s282b", cat: "Everyday Chat with Friends", id_text: "Sama, dong", en: "Same here", note: "" },
  { id: "s283b", cat: "Everyday Chat with Friends", id_text: "Nggak nyangka", en: "I didn't expect that", note: "" },
  { id: "s284b", cat: "Everyday Chat with Friends", id_text: "Asli deh", en: "Seriously / for real", note: "" },
  { id: "s285b", cat: "Everyday Chat with Friends", id_text: "Random banget", en: "So random", note: "" },
  { id: "s286b", cat: "Everyday Chat with Friends", id_text: "Gapapa kok", en: "It's fine, don't worry", note: "" },
  { id: "s287b", cat: "Everyday Chat with Friends", id_text: "Ini seru banget", en: "This is so much fun", note: "" },
  { id: "s288b", cat: "Everyday Chat with Friends", id_text: "Gue penasaran", en: "I'm curious", note: "" },
  { id: "s289b", cat: "Everyday Chat with Friends", id_text: "Coba deh", en: "Try it", note: "" },
  { id: "s290b", cat: "Everyday Chat with Friends", id_text: "Gue traktir", en: "I'll treat you", note: "Offering to pay for someone." },
  { id: "s291b", cat: "Everyday Chat with Friends", id_text: "Wah, makasih banyak", en: "Wow, thanks a lot", note: "" },
  { id: "s292b", cat: "Everyday Chat with Friends", id_text: "Sama-sama, santai aja", en: "You're welcome, no worries", note: "" },
  { id: "s293b", cat: "Everyday Chat with Friends", id_text: "Udah makan belum?", en: "Have you eaten yet?", note: "Extremely common friendly greeting, similar to \"how's it going.\"" },
  { id: "s294b", cat: "Everyday Chat with Friends", id_text: "Belum, lo?", en: "Not yet, you?", note: "" },
  { id: "s295b", cat: "Everyday Chat with Friends", id_text: "Cus", en: "Let's go", note: "Very casual slang." },
  { id: "s296b", cat: "Everyday Chat with Friends", id_text: "Gas terus!", en: "Keep going! / Let's do it!", note: "" },
  { id: "s297b", cat: "Everyday Chat with Friends", id_text: "Kocak banget", en: "So hilarious", note: "" },
  { id: "s298b", cat: "Everyday Chat with Friends", id_text: "Nggak sabar!", en: "Can't wait!", note: "" },
  { id: "s299b", cat: "Everyday Chat with Friends", id_text: "Gue baru sampai", en: "I just arrived", note: "" },
  { id: "s300b", cat: "Everyday Chat with Friends", id_text: "Otw", en: "On the way", note: "Widely used abbreviation, even in Indonesian texting." },

  // ---- Greetings & Politeness ----
  { id: "s001", cat: "Greetings & Politeness", id_text: "Halo", en: "Hello", note: "" },
  { id: "s002", cat: "Greetings & Politeness", id_text: "Selamat pagi", en: "Good morning", note: "" },
  { id: "s003", cat: "Greetings & Politeness", id_text: "Selamat siang", en: "Good afternoon", note: "Roughly 11am–3pm." },
  { id: "s004", cat: "Greetings & Politeness", id_text: "Selamat sore", en: "Good afternoon/evening", note: "Roughly 3pm–6pm." },
  { id: "s005", cat: "Greetings & Politeness", id_text: "Selamat malam", en: "Good evening/night", note: "" },
  { id: "s006", cat: "Greetings & Politeness", id_text: "Selamat tidur", en: "Good night", note: "Said when someone's going to sleep." },
  { id: "s007", cat: "Greetings & Politeness", id_text: "Apa kabar?", en: "How are you?", note: "" },
  { id: "s008", cat: "Greetings & Politeness", id_text: "Baik, terima kasih", en: "I'm good, thank you", note: "" },
  { id: "s009", cat: "Greetings & Politeness", id_text: "Baik-baik saja", en: "I'm fine", note: "" },
  { id: "s010", cat: "Greetings & Politeness", id_text: "Terima kasih", en: "Thank you", note: "" },
  { id: "s011", cat: "Greetings & Politeness", id_text: "Terima kasih banyak", en: "Thank you very much", note: "" },
  { id: "s012", cat: "Greetings & Politeness", id_text: "Sama-sama", en: "You're welcome", note: "" },
  { id: "s013", cat: "Greetings & Politeness", id_text: "Tolong", en: "Please", note: "Used when asking someone to do something." },
  { id: "s014", cat: "Greetings & Politeness", id_text: "Silakan", en: "Please / go ahead", note: "Used when offering or inviting." },
  { id: "s015", cat: "Greetings & Politeness", id_text: "Permisi", en: "Excuse me", note: "" },
  { id: "s016", cat: "Greetings & Politeness", id_text: "Maaf", en: "Sorry / excuse me", note: "" },
  { id: "s017", cat: "Greetings & Politeness", id_text: "Maaf, saya tidak mengerti", en: "Sorry, I don't understand", note: "" },
  { id: "s018", cat: "Greetings & Politeness", id_text: "Boleh saya bertanya?", en: "May I ask something?", note: "" },
  { id: "s019", cat: "Greetings & Politeness", id_text: "Nama saya Tony", en: "My name is Tony", note: "" },
  { id: "s020", cat: "Greetings & Politeness", id_text: "Siapa nama kamu?", en: "What's your name?", note: "" },
  { id: "s021", cat: "Greetings & Politeness", id_text: "Senang bertemu dengan kamu", en: "Nice to meet you", note: "" },
  { id: "s022", cat: "Greetings & Politeness", id_text: "Sampai jumpa", en: "See you later", note: "" },
  { id: "s023", cat: "Greetings & Politeness", id_text: "Sampai besok", en: "See you tomorrow", note: "" },
  { id: "s024", cat: "Greetings & Politeness", id_text: "Selamat tinggal", en: "Goodbye", note: "Said by the person leaving." },
  { id: "s025", cat: "Greetings & Politeness", id_text: "Selamat jalan", en: "Goodbye / safe travels", note: "Said to the person leaving." },
  { id: "s026", cat: "Greetings & Politeness", id_text: "Iya", en: "Yes", note: "" },
  { id: "s027", cat: "Greetings & Politeness", id_text: "Tidak", en: "No", note: "" },
  { id: "s028", cat: "Greetings & Politeness", id_text: "Tidak apa-apa", en: "It's okay / no worries", note: "" },
  { id: "s029", cat: "Greetings & Politeness", id_text: "Bisa tolong bantu saya?", en: "Can you please help me?", note: "" },
  { id: "s030", cat: "Greetings & Politeness", id_text: "Saya dari Australia", en: "I'm from Australia", note: "" },
  { id: "s031", cat: "Greetings & Politeness", id_text: "Saya belajar bahasa Indonesia", en: "I'm learning Indonesian", note: "" },
  { id: "s032", cat: "Greetings & Politeness", id_text: "Bahasa Indonesia saya masih belajar", en: "My Indonesian is still basic", note: "A humble, disarming thing to say." },
  { id: "s033", cat: "Greetings & Politeness", id_text: "Boleh saya minta tolong?", en: "May I ask for a favor?", note: "" },
  { id: "s034", cat: "Greetings & Politeness", id_text: "Tidak masalah", en: "No problem", note: "" },
  { id: "s035", cat: "Greetings & Politeness", id_text: "Semoga harimu menyenangkan", en: "Have a nice day", note: "" },

  // ---- Food & Dining ----
  { id: "s101", cat: "Food & Dining", id_text: "Saya lapar", en: "I'm hungry", note: "" },
  { id: "s102", cat: "Food & Dining", id_text: "Saya haus", en: "I'm thirsty", note: "" },
  { id: "s103", cat: "Food & Dining", id_text: "Enak!", en: "Delicious!", note: "" },
  { id: "s104", cat: "Food & Dining", id_text: "Enak banget!", en: "So delicious!", note: "" },
  { id: "s105", cat: "Food & Dining", id_text: "Ini enak sekali", en: "This is very delicious", note: "" },
  { id: "s106", cat: "Food & Dining", id_text: "Nasi goreng", en: "Fried rice", note: "" },
  { id: "s107", cat: "Food & Dining", id_text: "Mie goreng", en: "Fried noodles", note: "" },
  { id: "s108", cat: "Food & Dining", id_text: "Sate ayam", en: "Chicken satay", note: "" },
  { id: "s109", cat: "Food & Dining", id_text: "Rendang", en: "Rendang (spiced beef stew)", note: "" },
  { id: "s110", cat: "Food & Dining", id_text: "Gado-gado", en: "Gado-gado (vegetable salad with peanut sauce)", note: "" },
  { id: "s111", cat: "Food & Dining", id_text: "Ayam goreng", en: "Fried chicken", note: "" },
  { id: "s112", cat: "Food & Dining", id_text: "Nasi putih", en: "Plain white rice", note: "" },
  { id: "s113", cat: "Food & Dining", id_text: "Sayur", en: "Vegetables", note: "" },
  { id: "s114", cat: "Food & Dining", id_text: "Buah", en: "Fruit", note: "" },
  { id: "s115", cat: "Food & Dining", id_text: "Air putih", en: "Plain/still water", note: "" },
  { id: "s116", cat: "Food & Dining", id_text: "Kopi", en: "Coffee", note: "" },
  { id: "s117", cat: "Food & Dining", id_text: "Teh", en: "Tea", note: "" },
  { id: "s118", cat: "Food & Dining", id_text: "Teh manis", en: "Sweet tea", note: "" },
  { id: "s119", cat: "Food & Dining", id_text: "Es teh", en: "Iced tea", note: "" },
  { id: "s120", cat: "Food & Dining", id_text: "Es kelapa", en: "Iced coconut drink", note: "" },
  { id: "s121", cat: "Food & Dining", id_text: "Saya mau pesan ini", en: "I'd like to order this", note: "" },
  { id: "s122", cat: "Food & Dining", id_text: "Bisa minta menu?", en: "Can I get a menu, please?", note: "" },
  { id: "s123", cat: "Food & Dining", id_text: "Tidak pedas, ya", en: "Not spicy, please", note: "" },
  { id: "s124", cat: "Food & Dining", id_text: "Pedas sekali!", en: "Very spicy!", note: "" },
  { id: "s125", cat: "Food & Dining", id_text: "Saya alergi kacang", en: "I'm allergic to peanuts", note: "" },
  { id: "s126", cat: "Food & Dining", id_text: "Saya vegetarian", en: "I'm a vegetarian", note: "" },
  { id: "s127", cat: "Food & Dining", id_text: "Enaknya masakan kamu!", en: "Your cooking is so delicious!", note: "" },
  { id: "s128", cat: "Food & Dining", id_text: "Boleh tambah lagi?", en: "Can I have more, please?", note: "" },
  { id: "s129", cat: "Food & Dining", id_text: "Saya kenyang", en: "I'm full", note: "" },
  { id: "s130", cat: "Food & Dining", id_text: "Kenyang banget!", en: "So full!", note: "" },
  { id: "s131", cat: "Food & Dining", id_text: "Minta bon", en: "Can I get the bill, please", note: "" },
  { id: "s132", cat: "Food & Dining", id_text: "Berapa semuanya?", en: "How much is it all?", note: "" },
  { id: "s133", cat: "Food & Dining", id_text: "Enak, terima kasih sudah masak", en: "Delicious, thank you for cooking", note: "" },
  { id: "s134", cat: "Food & Dining", id_text: "Ini favorit saya", en: "This is my favorite", note: "" },
  { id: "s135", cat: "Food & Dining", id_text: "Mau coba?", en: "Want to try some?", note: "" },
  { id: "s136", cat: "Food & Dining", id_text: "Sedap!", en: "Tasty!", note: "Another common word for delicious." },
  { id: "s137", cat: "Food & Dining", id_text: "Sarapan", en: "Breakfast", note: "" },
  { id: "s138", cat: "Food & Dining", id_text: "Makan siang", en: "Lunch", note: "" },
  { id: "s139", cat: "Food & Dining", id_text: "Makan malam", en: "Dinner", note: "" },
  { id: "s140", cat: "Food & Dining", id_text: "Camilan", en: "Snack", note: "" },
  { id: "s141", cat: "Food & Dining", id_text: "Manis", en: "Sweet", note: "" },
  { id: "s142", cat: "Food & Dining", id_text: "Asin", en: "Salty", note: "" },
  { id: "s143", cat: "Food & Dining", id_text: "Asam", en: "Sour", note: "" },
  { id: "s144", cat: "Food & Dining", id_text: "Pahit", en: "Bitter", note: "" },
  { id: "s145", cat: "Food & Dining", id_text: "Selamat makan", en: "Enjoy your meal", note: "" },

  // ---- Directions & Getting Around ----
  { id: "s151", cat: "Directions & Getting Around", id_text: "Di mana toilet?", en: "Where's the toilet?", note: "" },
  { id: "s152", cat: "Directions & Getting Around", id_text: "Di mana ini?", en: "Where is this?", note: "" },
  { id: "s153", cat: "Directions & Getting Around", id_text: "Kiri", en: "Left", note: "" },
  { id: "s154", cat: "Directions & Getting Around", id_text: "Kanan", en: "Right", note: "" },
  { id: "s155", cat: "Directions & Getting Around", id_text: "Lurus", en: "Straight ahead", note: "" },
  { id: "s156", cat: "Directions & Getting Around", id_text: "Belok kiri", en: "Turn left", note: "" },
  { id: "s157", cat: "Directions & Getting Around", id_text: "Belok kanan", en: "Turn right", note: "" },
  { id: "s158", cat: "Directions & Getting Around", id_text: "Dekat", en: "Near", note: "" },
  { id: "s159", cat: "Directions & Getting Around", id_text: "Jauh", en: "Far", note: "" },
  { id: "s160", cat: "Directions & Getting Around", id_text: "Berapa jauh dari sini?", en: "How far is it from here?", note: "" },
  { id: "s161", cat: "Directions & Getting Around", id_text: "Saya tersesat", en: "I'm lost", note: "" },
  { id: "s162", cat: "Directions & Getting Around", id_text: "Bisa antar saya ke sini?", en: "Can you take me here?", note: "" },
  { id: "s163", cat: "Directions & Getting Around", id_text: "Tolong berhenti di sini", en: "Please stop here", note: "To a driver." },
  { id: "s164", cat: "Directions & Getting Around", id_text: "Bandara", en: "Airport", note: "" },
  { id: "s165", cat: "Directions & Getting Around", id_text: "Stasiun", en: "Station", note: "" },
  { id: "s166", cat: "Directions & Getting Around", id_text: "Terminal bis", en: "Bus terminal", note: "" },
  { id: "s167", cat: "Directions & Getting Around", id_text: "Hotel", en: "Hotel", note: "" },
  { id: "s168", cat: "Directions & Getting Around", id_text: "Alamat", en: "Address", note: "" },
  { id: "s169", cat: "Directions & Getting Around", id_text: "Ini alamatnya", en: "This is the address", note: "" },
  { id: "s170", cat: "Directions & Getting Around", id_text: "Naik apa ke sana?", en: "How do I get there?", note: "" },
  { id: "s171", cat: "Directions & Getting Around", id_text: "Naik taksi", en: "Take a taxi", note: "" },
  { id: "s172", cat: "Directions & Getting Around", id_text: "Naik ojek", en: "Take a motorbike taxi", note: "" },
  { id: "s173", cat: "Directions & Getting Around", id_text: "Jalan kaki", en: "Walk", note: "" },
  { id: "s174", cat: "Directions & Getting Around", id_text: "Berapa lama dari sini?", en: "How long from here?", note: "" },
  { id: "s175", cat: "Directions & Getting Around", id_text: "Macet", en: "Traffic jam", note: "" },
  { id: "s176", cat: "Directions & Getting Around", id_text: "Hati-hati", en: "Be careful", note: "" },
  { id: "s177", cat: "Directions & Getting Around", id_text: "Awas!", en: "Watch out!", note: "" },
  { id: "s178", cat: "Directions & Getting Around", id_text: "Pelan-pelan", en: "Slowly / take it easy", note: "" },
  { id: "s179", cat: "Directions & Getting Around", id_text: "Cepat", en: "Fast", note: "" },
  { id: "s180", cat: "Directions & Getting Around", id_text: "Tunggu sebentar", en: "Wait a moment", note: "" },
  { id: "s181", cat: "Directions & Getting Around", id_text: "Sudah sampai", en: "We've arrived", note: "" },
  { id: "s182", cat: "Directions & Getting Around", id_text: "Masih jauh?", en: "Is it still far?", note: "" },
  { id: "s183", cat: "Directions & Getting Around", id_text: "Boleh saya lihat peta?", en: "May I see the map?", note: "" },
  { id: "s184", cat: "Directions & Getting Around", id_text: "Ini di sebelah mana?", en: "Which side is this on?", note: "" },
  { id: "s185", cat: "Directions & Getting Around", id_text: "Pintu keluar", en: "Exit", note: "" },

  // ---- Shopping & Bargaining ----
  { id: "s186", cat: "Shopping & Bargaining", id_text: "Berapa harganya?", en: "How much is it?", note: "" },
  { id: "s187", cat: "Shopping & Bargaining", id_text: "Mahal", en: "Expensive", note: "" },
  { id: "s188", cat: "Shopping & Bargaining", id_text: "Murah", en: "Cheap", note: "" },
  { id: "s189", cat: "Shopping & Bargaining", id_text: "Terlalu mahal", en: "Too expensive", note: "" },
  { id: "s190", cat: "Shopping & Bargaining", id_text: "Bisa kurang?", en: "Can you lower the price?", note: "Standard bargaining phrase." },
  { id: "s191", cat: "Shopping & Bargaining", id_text: "Boleh diskon?", en: "Can I get a discount?", note: "" },
  { id: "s192", cat: "Shopping & Bargaining", id_text: "Saya cuma lihat-lihat", en: "I'm just looking", note: "" },
  { id: "s193", cat: "Shopping & Bargaining", id_text: "Saya mau beli ini", en: "I want to buy this", note: "" },
  { id: "s194", cat: "Shopping & Bargaining", id_text: "Ada warna lain?", en: "Is there another color?", note: "" },
  { id: "s195", cat: "Shopping & Bargaining", id_text: "Ada ukuran lain?", en: "Is there another size?", note: "" },
  { id: "s196", cat: "Shopping & Bargaining", id_text: "Terlalu besar", en: "Too big", note: "" },
  { id: "s197", cat: "Shopping & Bargaining", id_text: "Terlalu kecil", en: "Too small", note: "" },
  { id: "s198", cat: "Shopping & Bargaining", id_text: "Pas", en: "Just right / fits well", note: "" },
  { id: "s199", cat: "Shopping & Bargaining", id_text: "Bisa dicoba?", en: "Can I try it on?", note: "" },
  { id: "s200a", cat: "Shopping & Bargaining", id_text: "Uang kembalian", en: "Change (money)", note: "" },
  { id: "s200c", cat: "Shopping & Bargaining", id_text: "Bayar pakai kartu bisa?", en: "Can I pay by card?", note: "" },
  { id: "s200d", cat: "Shopping & Bargaining", id_text: "Bayar cash saja", en: "I'll pay cash", note: "" },
  { id: "s200e", cat: "Shopping & Bargaining", id_text: "Ada yang lebih murah?", en: "Is there a cheaper one?", note: "" },
  { id: "s200f", cat: "Shopping & Bargaining", id_text: "Pas segini saja", en: "This price is fine", note: "Agreeing to close a bargain." },
  { id: "s200g", cat: "Shopping & Bargaining", id_text: "Oke, deal", en: "Okay, deal", note: "" },
  { id: "s200h", cat: "Shopping & Bargaining", id_text: "Tidak jadi", en: "Never mind, I won't", note: "Backing out of buying something." },
  { id: "s200i", cat: "Shopping & Bargaining", id_text: "Pasar", en: "Market", note: "" },
  { id: "s200j", cat: "Shopping & Bargaining", id_text: "Toko", en: "Shop", note: "" },
  { id: "s200k", cat: "Shopping & Bargaining", id_text: "Bisa bungkus?", en: "Can you wrap/pack it?", note: "" },
  { id: "s200l", cat: "Shopping & Bargaining", id_text: "Sudah pas harganya", en: "The price is fair now", note: "" },

  // ---- Numbers & Time ----
  { id: "s401", cat: "Numbers & Time", id_text: "Satu", en: "One", note: "" },
  { id: "s402", cat: "Numbers & Time", id_text: "Dua", en: "Two", note: "" },
  { id: "s403", cat: "Numbers & Time", id_text: "Tiga", en: "Three", note: "" },
  { id: "s404", cat: "Numbers & Time", id_text: "Empat", en: "Four", note: "" },
  { id: "s405", cat: "Numbers & Time", id_text: "Lima", en: "Five", note: "" },
  { id: "s406", cat: "Numbers & Time", id_text: "Enam", en: "Six", note: "" },
  { id: "s407", cat: "Numbers & Time", id_text: "Tujuh", en: "Seven", note: "" },
  { id: "s408", cat: "Numbers & Time", id_text: "Delapan", en: "Eight", note: "" },
  { id: "s409", cat: "Numbers & Time", id_text: "Sembilan", en: "Nine", note: "" },
  { id: "s410", cat: "Numbers & Time", id_text: "Sepuluh", en: "Ten", note: "" },
  { id: "s411", cat: "Numbers & Time", id_text: "Dua puluh", en: "Twenty", note: "" },
  { id: "s412", cat: "Numbers & Time", id_text: "Lima puluh", en: "Fifty", note: "" },
  { id: "s413", cat: "Numbers & Time", id_text: "Seratus", en: "One hundred", note: "" },
  { id: "s414", cat: "Numbers & Time", id_text: "Seribu", en: "One thousand", note: "" },
  { id: "s415", cat: "Numbers & Time", id_text: "Sejam", en: "One hour", note: "" },
  { id: "s416", cat: "Numbers & Time", id_text: "Setengah jam", en: "Half an hour", note: "" },
  { id: "s417", cat: "Numbers & Time", id_text: "Jam berapa sekarang?", en: "What time is it now?", note: "" },
  { id: "s418", cat: "Numbers & Time", id_text: "Pukul berapa kita bertemu?", en: "What time shall we meet?", note: "" },
  { id: "s419", cat: "Numbers & Time", id_text: "Hari ini", en: "Today", note: "" },
  { id: "s420", cat: "Numbers & Time", id_text: "Besok", en: "Tomorrow", note: "" },
  { id: "s421", cat: "Numbers & Time", id_text: "Kemarin", en: "Yesterday", note: "" },
  { id: "s422", cat: "Numbers & Time", id_text: "Minggu depan", en: "Next week", note: "" },
  { id: "s423", cat: "Numbers & Time", id_text: "Sekarang", en: "Now", note: "" },
  { id: "s424", cat: "Numbers & Time", id_text: "Nanti", en: "Later", note: "" },
  { id: "s425", cat: "Numbers & Time", id_text: "Pagi", en: "Morning", note: "" },
  { id: "s426", cat: "Numbers & Time", id_text: "Siang", en: "Midday / afternoon", note: "" },
  { id: "s427", cat: "Numbers & Time", id_text: "Malam", en: "Night", note: "" },
  { id: "s428", cat: "Numbers & Time", id_text: "Jam sepuluh pagi", en: "Ten a.m.", note: "" },
  { id: "s429", cat: "Numbers & Time", id_text: "Jam tujuh malam", en: "Seven p.m.", note: "" },
  { id: "s430", cat: "Numbers & Time", id_text: "Berapa lama?", en: "How long does it take?", note: "" },

  // ---- Emergencies & Health ----
  { id: "s501", cat: "Emergencies & Health", id_text: "Tolong!", en: "Help!", note: "" },
  { id: "s502", cat: "Emergencies & Health", id_text: "Saya butuh dokter", en: "I need a doctor", note: "" },
  { id: "s503", cat: "Emergencies & Health", id_text: "Panggil ambulans", en: "Call an ambulance", note: "" },
  { id: "s504", cat: "Emergencies & Health", id_text: "Saya sakit", en: "I'm sick / in pain", note: "" },
  { id: "s505", cat: "Emergencies & Health", id_text: "Kepala saya sakit", en: "My head hurts", note: "" },
  { id: "s506", cat: "Emergencies & Health", id_text: "Perut saya sakit", en: "My stomach hurts", note: "" },
  { id: "s507", cat: "Emergencies & Health", id_text: "Saya demam", en: "I have a fever", note: "" },
  { id: "s508", cat: "Emergencies & Health", id_text: "Apotek di mana?", en: "Where's the pharmacy?", note: "" },
  { id: "s509", cat: "Emergencies & Health", id_text: "Rumah sakit", en: "Hospital", note: "" },
  { id: "s510", cat: "Emergencies & Health", id_text: "Polisi", en: "Police", note: "" },
  { id: "s511", cat: "Emergencies & Health", id_text: "Ada kecelakaan", en: "There's been an accident", note: "" },
  { id: "s512", cat: "Emergencies & Health", id_text: "Saya kehilangan paspor", en: "I've lost my passport", note: "" },
  { id: "s513", cat: "Emergencies & Health", id_text: "Dompet saya hilang", en: "My wallet is missing", note: "" },
  { id: "s514", cat: "Emergencies & Health", id_text: "Saya butuh bantuan", en: "I need help", note: "" },
  { id: "s515", cat: "Emergencies & Health", id_text: "Ini darurat", en: "This is an emergency", note: "" },
  { id: "s516", cat: "Emergencies & Health", id_text: "Saya alergi obat ini", en: "I'm allergic to this medicine", note: "" },
  { id: "s517", cat: "Emergencies & Health", id_text: "Obat", en: "Medicine", note: "" },
  { id: "s518", cat: "Emergencies & Health", id_text: "Saya tidak apa-apa", en: "I'm okay", note: "Reassuring someone." },
  { id: "s519", cat: "Emergencies & Health", id_text: "Hati-hati di jalan", en: "Be safe on the road", note: "" },
  { id: "s520", cat: "Emergencies & Health", id_text: "Kunci hotel saya hilang", en: "My hotel key is missing", note: "" },
  { id: "s521", cat: "Emergencies & Health", id_text: "Bisa antar saya ke rumah sakit?", en: "Can you take me to the hospital?", note: "" },
  { id: "s522", cat: "Emergencies & Health", id_text: "Saya perlu istirahat", en: "I need to rest", note: "" },
  { id: "s523", cat: "Emergencies & Health", id_text: "Saya pusing", en: "I feel dizzy", note: "" },
  { id: "s524", cat: "Emergencies & Health", id_text: "Nomor telepon darurat", en: "Emergency phone number", note: "" },
  { id: "s525", cat: "Emergencies & Health", id_text: "Semua baik-baik saja", en: "Everything's fine", note: "" },
];

// Category display order for the Suggestions tab — Romantic and Funny & Playful come first
// since that's what Tony specifically wants to work through early on.
const SUGGESTION_CATEGORY_ORDER = [
  "Romantic",
  "Funny & Playful",
  "Meeting Her Family",
  "Everyday Chat with Friends",
  "Greetings & Politeness",
  "Food & Dining",
  "Directions & Getting Around",
  "Shopping & Bargaining",
  "Numbers & Time",
  "Emergencies & Health",
];
